### ISSUE TITLE
Celery backend: Handle other serializers than pickle (JSON)

### ISSUE THREAD

**Issue by davidfischer-ch** [bameda/djmail#22]
When switching to the Celery back-end I have an issue: The parameters for the task, "emails" are instances of django.core.mail.message.EmailMessage or EmailMultiAlternatives. There are both not serializable to JSON. We do not use pickle as recommended by Celery's documentation.

I will look at it tomorrow but in the meantime if you have any idea to fix it, thanks for sharing.

**Comment by davidfischer-ch** [comment]
I guess its fixed now?

**Comment by bameda** [comment]
Yes, and I've published a new version of djmail.

**Comment by abodacs** [comment]
@davidfischer-ch Celery back end doesnot work for me could you make gist of your configuration for it ??
