### ISSUE TITLE
Celery backend fails when CELERY_TASK_SERIALIZER not defined

### ISSUE THREAD

**Issue by ryanpineo** [bameda/djmail#36]
Celery defaults the setting `CELERY_TASK_SERIALIZER` to `'picke'` so there is no guarantee that a Django project will set it.

**Comment by mathieuhinderyckx** [comment]
Celery 4.x now [defaults the setting to json](https://github.com/celery/celery/blob/00af0e8caae2f052631b57323535ca2ebd4ec0da/docs/whatsnew-4.0.rst#json-is-now-the-default-serializer), so this is no longer an issue:

**Comment by ryanpineo** [comment]
Celery has always had a default, it used to be pickle.  The issue still remains because a Django project might not set `CELERY_TASK_SERIALIZER` if they are happy with the default.

**Comment by mathieuhinderyckx** [comment]
You're right, I mixed up the two. I changed it to use 'json' if the setting is not explicitly defined in the Django settings.
