### ISSUE TITLE
class NoArgsCommand removed in django 1.10

### ISSUE THREAD

**Issue by joreninghelbrecht** [bameda/djmail#37]
https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10

The class BaseCommand should be used instead: https://docs.djangoproject.com/ja/1.10/internals/deprecation/#deprecation-removed-in-1-10

Note:

> Subclassing the BaseCommand class requires that you implement the handle() method.

https://docs.djangoproject.com/ja/1.10/howto/custom-management-commands/#django.core.management.BaseCommand

**Comment by joreninghelbrecht** [comment]
Issue occurs here: djmail/djmail/management/commands/djmail_retry_send_messages.py

**Comment by bameda** [comment]
Yes you are right. I'll fix it this weekend and release a new version.

**Comment by bameda** [comment]
This was fixed in 0.13.1

**Comment by joreninghelbrecht** [comment]
Thanks a lot!!

**Comment by bameda** [comment]
You are welcome
