### ISSUE TITLE
Docs site is down

### ISSUE THREAD

**Issue by blag** [bameda/djmail#43]
The GitHub Pages site that hosts the documentation no longer exists: http://bameda.github.io/djmail/

**Comment by bameda** [comment]
Is strange, try with http://bameda.github.io/djmail/index.html

**Comment by bameda** [comment]
It was an issue in github

https://twitter.com/githubstatus/status/846354463451426817

and now is working again.

https://twitter.com/githubstatus/status/846362561721368576
